# Generated by Django 4.2.6 on 2023-10-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(blank=True, max_length=25, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Cimage')),
                ('No_tour_place', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
