# Generated by Django 4.2.6 on 2023-10-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(blank=True, max_length=25, null=True)),
                ('Place', models.CharField(blank=True, max_length=35, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='pimg')),
            ],
        ),
    ]
