# Generated by Django 4.2.6 on 2023-11-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_offer_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_db',
            name='Name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
