# Generated by Django 4.2.6 on 2023-11-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_package_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeDetails_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(blank=True, max_length=30, null=True)),
                ('Country', models.CharField(blank=True, max_length=30, null=True)),
                ('Details', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='PlaceDetails')),
            ],
        ),
    ]
