# Generated by Django 4.2.6 on 2023-11-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_placedetails_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(blank=True, max_length=30, null=True)),
                ('Place', models.CharField(blank=True, max_length=30, null=True)),
                ('Suite', models.CharField(blank=True, max_length=50, null=True)),
                ('Details', models.CharField(blank=True, max_length=30, null=True)),
                ('Rating', models.CharField(blank=True, max_length=30, null=True)),
                ('Hotel', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('Discount', models.IntegerField(blank=True, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='package')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='package')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='package')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='package')),
            ],
        ),
    ]
