# Generated by Django 4.2.6 on 2023-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_remove_hotel_db_suite_hotel_db_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(blank=True, max_length=100, null=True)),
                ('To', models.CharField(blank=True, max_length=100, null=True)),
                ('From_City', models.CharField(blank=True, max_length=100, null=True)),
                ('From_country', models.CharField(blank=True, max_length=100, null=True)),
                ('To_city', models.CharField(blank=True, max_length=100, null=True)),
                ('To_Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Flight_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Flight_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Depature_time', models.CharField(blank=True, max_length=100, null=True)),
                ('Landing_time', models.CharField(blank=True, max_length=100, null=True)),
                ('Charge', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
