# Generated by Django 4.2.6 on 2023-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_hotelbooking_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blogs')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blogs')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('detail', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
