# Generated by Django 4.2.6 on 2023-11-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_blog_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_booking_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(blank=True, max_length=30, null=True)),
                ('Hotel_name', models.CharField(blank=True, max_length=50, null=True)),
                ('First_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Second_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=80, null=True)),
                ('No_of_guest', models.CharField(blank=True, max_length=30, null=True)),
                ('Arrive_date', models.CharField(blank=True, max_length=30, null=True)),
                ('Arrive_time', models.CharField(blank=True, max_length=30, null=True)),
                ('Arrive_apm', models.CharField(blank=True, max_length=30, null=True)),
                ('Checkout', models.CharField(blank=True, max_length=30, null=True)),
                ('Pickup', models.CharField(blank=True, max_length=30, null=True)),
                ('Flight', models.CharField(blank=True, max_length=40, null=True)),
                ('Request', models.CharField(blank=True, max_length=500, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Bill', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
