# Generated by Django 4.2.6 on 2023-11-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_hotel_booking_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_booking_db',
            name='Room',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
