# Generated by Django 4.2.6 on 2023-11-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_hotel_booking_db_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
