# Generated by Django 4.2.6 on 2023-11-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_subscription_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('payment_id', models.CharField(max_length=200)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
