# Generated by Django 4.2.6 on 2023-11-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_sub_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_db',
            name='email',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
