# Generated by Django 4.2.6 on 2023-12-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_alter_subscription_db_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_db',
            name='Country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register_db',
            name='Place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
