# Generated by Django 4.2.6 on 2023-12-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_register_db_country_register_db_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_db',
            name='Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
