# Generated by Django 4.2.6 on 2023-12-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_register_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_payment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
