# Generated by Django 4.2.6 on 2023-12-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_alter_sub_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_payment',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sub_payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
