# Generated by Django 4.2.6 on 2023-12-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='review_db',
        ),
    ]
