# Generated by Django 4.2.6 on 2023-12-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_rename_review_review_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_booking_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('First_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Second_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Email', models.EmailField(blank=True, max_length=80, null=True)),
                ('Type', models.CharField(blank=True, max_length=80, null=True)),
                ('No_person', models.IntegerField(blank=True, null=True)),
                ('Date', models.CharField(blank=True, max_length=40, null=True)),
                ('Flight', models.CharField(blank=True, max_length=100, null=True)),
                ('Flight_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
