# Generated by Django 4.2.6 on 2023-12-27 10:40

import Frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0016_flight_booking_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_booking_db',
            name='Date',
            field=models.DateField(blank=True, null=True, validators=[Frontend.models.validate_future_date]),
        ),
    ]
