# Generated by Django 4.2.6 on 2023-12-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0017_alter_flight_booking_db_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_booking_db',
            name='Time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
