# Generated by Django 4.2.6 on 2023-12-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0018_flight_booking_db_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_db',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
